import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import { PropsWithChildren } from 'react'

const poppins = Poppins({ subsets: ['latin'], weight: ['400'] })

export const metadata: Metadata = {
  title: 'TeamGuru',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
