import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import { PropsWithChildren } from 'react'

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '600'] })

export const metadata: Metadata = {
  title: 'TeamGuru',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} bg-slate-200 h-screen text-slate-800`}
      >
        {children}
      </body>
    </html>
  )
}
